### ISSUE TITLE
Custom Commands on Win/Lose

### ISSUE THREAD

**Issue by TheMeq** [caseif/MGLib#10]
Hello Caseif, please can you implement the option to run custom commands on win and lose so we can dish out awards depending on the end game? This may need rolling out to the minigames as well so that they have the ability to run it.

**Comment by caseif** [comment]
Unfoetunately, I'll be discontinuing MGLib after the next uodate, so no new features will be added in the future. That being said, I'll be replacing it with [Flint](https://github.com/caseif/Flint), which is essentially a better-thought-out version of MGLib. I'll need to consider whether this ticket falls within its scope, or if it should be implemented by TTT (which is where I assume you're coming from) instead. I'll keep you posted when I decide, though.
